### ISSUE TITLE
Refactor `validate_pagination_params` to avoid redundancy with async-graphql's internal checks

### ISSUE THREAD

**Issue by msk** [aicers/review-web#328]
The `validate_pagination_params` function currently (as of 7fccd0a) performs several checks on pagination parameters (first, last, before, and after) that are already handled by the async-graphql crate. Since async-graphql adheres to the [GraphQL Cursor Connections Specification](https://relay.dev/graphql/connections.htm), it ensures that:

- Only one of `first` and `last` is present.
- The values of `first` and `last` are non-negative integers.

As a result, some of the validations in `validate_pagination_params` are redundant. These checks should be refactored to focus on enforcing additional requirements specific to review-web's API, rather than duplicating checks that async-graphql already handles.

**Comment by sehkone** [comment]
Aside from the redundancy you pointed out, I’ve been thinking about why the extra validation that `async_graphql::connection::query` doesn’t enforce was introduced. It was actually added in #167, and at the time, I thought the extra validation was necessary because `async_graphql` did not provide the complete validation required by certain conventions or standards. However, based on what you mentioned, the `async_graphql::connection::query` follows the [GraphQL Cursor Connections Specification](https://relay.dev/graphql/connections.htm), so adding more enforcement beyond what the specification requires might not be necessary.

What do you think about this? If you agree, I’ll remove the `validate_pagination_params` method, leaving only `async_graphql::connection::query` to handle the validation. Previously, removing this wouldn't have worked because some APIs didn’t use `async_graphql::connection::query`. But now that they all do, simplifying things by eliminating `validate_pagination_params` seems reasonable.

**Comment by sehkone** [comment]
However, one thing should remain, so we cannot eliminate all the features that the `validate_pagination_params` provide:

```rust
(false, false, false, _) => {
     first = Some(DEFAULT_CONNECTION_SIZE);
}
(false, false, true, false) => {
     last = Some(DEFAULT_CONNECTION_SIZE);
}
```

It might be reasonable to rename it to `check_connection_size` with the above.

**Comment by msk** [comment]
From what I understand, some of our paginated APIs weren't fully implementing the GraphQL Cursor Connections Specification, and the extra validation was added as a safeguard. Specifically, some APIs weren't ready to handle both `before` and `after` parameters, either due to lack of implementation or insufficient testing.

However, I completely agree with you that we shouldn't impose additional constraints beyond what the Specification requires. Instead, we should focus on ensuring that all our paginated APIs are fully compliant with the Specification. This means that those APIs lacking proper handling of certain parameter combinations should be improved to meet the standard.
